insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('B','水库');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('D','堤防(段)');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('E','海堤');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('F','蓄滞(行)洪区');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('H','圩垸');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('K','水闸');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('N','治河工程');
insert into TB_GCLB(GCFLDM,GCFLMC)VALUES('P','穿堤建筑物');