document.write("<table width='100%' border='0' cellspacing='0' cellpadding='0'>");
document.write("  <tr> ");
document.write("    <td valign='middle' align='left' width='30%'> ");
document.write("      <select name='xzqhdm1' onchange=click1(this.value);document.all.xzqh.value=this.value>");
document.write("    <option value=000000>全部                                </option>");
document.write("    <option value=110000>北京市                              </option>");
document.write("    <option value=120000>天津市                              </option>");
document.write("    <option value=130000>河北省                              </option>");
document.write("    <option value=140000>山西省                              </option>");
document.write("    <option value=150000>内蒙古自治区                        </option>");
document.write("    <option value=210000>辽宁省                              </option>");
document.write("    <option value=220000>吉林省                              </option>");
document.write("    <option value=230000>黑龙江省                            </option>");
document.write("    <option value=310000>上海市                              </option>");
document.write("    <option value=320000>江苏省                              </option>");
document.write("    <option value=330000>浙江省                              </option>");
document.write("    <option value=340000>安徽省                              </option>");
document.write("    <option value=350000>福建省                              </option>");
document.write("    <option value=360000>江西省                              </option>");
document.write("    <option value=370000>山东省                              </option>");
document.write("    <option value=410000>河南省                              </option>");
document.write("    <option value=420000>湖北省                              </option>");
document.write("    <option value=430000>湖南省                              </option>");
document.write("    <option value=440000>广东省                              </option>");
document.write("    <option value=450000>广西壮族自治区                      </option>");
document.write("    <option value=460000>海南省                              </option>");
document.write("    <option value=500000>重庆市                              </option>");
document.write("    <option value=510000>四川省                              </option>");
document.write("    <option value=520000>贵州省                              </option>");
document.write("    <option value=530000>云南省                              </option>");
document.write("    <option value=540000>西藏自治区                          </option>");
document.write("    <option value=610000>陕西省                              </option>");
document.write("    <option value=620000>甘肃省                              </option>");
document.write("    <option value=630000>青海省                              </option>");
document.write("    <option value=640000>宁夏回族自治区                      </option>");
document.write("    <option value=650000>新疆维吾尔自治区                    </option>");
document.write("    <option value=710000>台湾                                </option>");
document.write("    <option value=720000>香港                                </option>");
document.write("    <option value=730000>澳门                                </option>");
document.write(" </select>");
document.write("    </td>");
document.write("    <td align='left'  width='70%' valign='middle'> ");
document.write("      <table valign='middle' width='100%' border='0' cellspacing='0' cellpadding='0' align='left' >");

document.write("        <tr id=tr0 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=000000>全部                      </option>");
document.write("          </td>");
document.write("        </tr>");

document.write("        <tr id=tr1 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=110000>全部                      </option>");
document.write("    <option value=110100>北京市市辖区                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr2 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=120000>全部                      </option>");
document.write("    <option value=120100>天津市市辖区                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr3 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=130000>全部                      </option>");
document.write("    <option value=130100>石家庄市                      </option>");
document.write("    <option value=130200>唐山市                        </option>");
document.write("    <option value=130300>秦皇岛市                      </option>");
document.write("    <option value=130400>邯郸市                        </option>");
document.write("    <option value=130500>邢台市                        </option>");
document.write("    <option value=130600>保定市                        </option>");
document.write("    <option value=130700>张家口市                      </option>");
document.write("    <option value=130800>承德市                        </option>");
document.write("    <option value=130900>沧州市                        </option>");
document.write("    <option value=131000>廊坊市                        </option>");
document.write("    <option value=132100>邯郸地区                      </option>");
document.write("    <option value=132200>邢台地区                      </option>");
document.write("    <option value=132300>石家庄地区                    </option>");
document.write("    <option value=132400>保定地区                      </option>");
document.write("    <option value=132500>张家口地区                    </option>");
document.write("    <option value=132600>承德地区                      </option>");
document.write("    <option value=132900>沧州地区                      </option>");
document.write("    <option value=133000>衡水地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr4 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=140000>全部                      </option>");
document.write("    <option value=140100>太原市                        </option>");
document.write("    <option value=140200>大同市                        </option>");
document.write("    <option value=140300>阳泉市                        </option>");
document.write("    <option value=140400>长治市                        </option>");
document.write("    <option value=140500>晋城市                        </option>");
document.write("    <option value=140600>朔州市                        </option>");
document.write("    <option value=142100>雁北地区                      </option>");
document.write("    <option value=142200>忻州地区                      </option>");
document.write("    <option value=142300>吕梁地区                      </option>");
document.write("    <option value=142400>晋中地区                      </option>");
document.write("    <option value=142600>临汾地区                      </option>");
document.write("    <option value=142700>运城地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr5 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=150000>全部                      </option>");
document.write("    <option value=150100>呼和浩特市                    </option>");
document.write("    <option value=150200>包头市                        </option>");
document.write("    <option value=150300>乌海市                        </option>");
document.write("    <option value=150400>赤峰市                        </option>");
document.write("    <option value=152100>呼伦贝尔盟                    </option>");
document.write("    <option value=152200>兴安盟                        </option>");
document.write("    <option value=152300>哲里木盟                      </option>");
document.write("    <option value=152500>锡林郭勒盟                    </option>");
document.write("    <option value=152600>乌兰察布盟                    </option>");
document.write("    <option value=152700>伊克昭盟                      </option>");
document.write("    <option value=152800>巴彦淖尔盟                    </option>");
document.write("    <option value=152900>阿拉善盟                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr6 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=210000>全部                      </option>");
document.write("    <option value=210100>沈阳市                        </option>");
document.write("    <option value=210200>大连市                        </option>");
document.write("    <option value=210300>鞍山市                        </option>");
document.write("    <option value=210400>抚顺市                        </option>");
document.write("    <option value=210500>本溪市                        </option>");
document.write("    <option value=210600>丹东市                        </option>");
document.write("    <option value=210700>锦州市                        </option>");
document.write("    <option value=210800>营口市                        </option>");
document.write("    <option value=210900>阜新市                        </option>");
document.write("    <option value=211000>辽阳市                        </option>");
document.write("    <option value=211100>盘锦市                        </option>");
document.write("    <option value=211200>铁岭市                        </option>");
document.write("    <option value=211300>朝阳市                        </option>");
document.write("    <option value=211400>锦西市                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr7 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=220000>全部                      </option>");
document.write("    <option value=220100>长春市                        </option>");
document.write("    <option value=220200>吉林市                        </option>");
document.write("    <option value=220300>四平市                        </option>");
document.write("    <option value=220400>辽源市                        </option>");
document.write("    <option value=220500>通化市                        </option>");
document.write("    <option value=220600>浑江市                        </option>");
document.write("    <option value=222300>白城地区                      </option>");
document.write("    <option value=222400>延边朝鲜自治州                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr8 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=230000>全部                      </option>");
document.write("    <option value=230100>哈尔滨市                    </option>");
document.write("    <option value=230200>齐齐哈尔市                  </option>");
document.write("    <option value=230300>鸡西市                      </option>");
document.write("    <option value=230400>鹤岗市                      </option>");
document.write("    <option value=230500>双鸭山市                    </option>");
document.write("    <option value=230600>大庆市                      </option>");
document.write("    <option value=230700>伊春市                      </option>");
document.write("    <option value=230800>佳木斯市                    </option>");
document.write("    <option value=230900>七台河市                    </option>");
document.write("    <option value=231000>牡丹江市                    </option>");
document.write("    <option value=232100>松花江地区                  </option>");
document.write("    <option value=232300>绥化地区                    </option>");
document.write("    <option value=232600>黑河地区                    </option>");
document.write("    <option value=232700>大兴安岭地区                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr9 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=310000>全部                      </option>");
document.write("    <option value=310100>上海市市辖区                        </option>");
document.write("    <option value=310200>上海市县                            </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr10 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=320000>全部                      </option>");
document.write("    <option value=320100>南京市                        </option>");
document.write("    <option value=320200>无锡市                        </option>");
document.write("    <option value=320300>徐州市                        </option>");
document.write("    <option value=320400>常州市                        </option>");
document.write("    <option value=320500>苏州市                        </option>");
document.write("    <option value=320600>南通市                        </option>");
document.write("    <option value=320700>连云港市                      </option>");
document.write("    <option value=320800>淮阴市                        </option>");
document.write("    <option value=320900>盐城市                        </option>");
document.write("    <option value=321000>扬州市                        </option>");
document.write("    <option value=321100>镇江市                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr11 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=330000>全部                      </option>");
document.write("    <option value=330100>杭州市                        </option>");
document.write("    <option value=330200>宁波市                        </option>");
document.write("    <option value=330300>温州市                        </option>");
document.write("    <option value=330400>嘉兴市                        </option>");
document.write("    <option value=330500>湖洲市                        </option>");
document.write("    <option value=330600>绍兴市                        </option>");
document.write("    <option value=330700>金华市                        </option>");
document.write("    <option value=330800>衢州市                        </option>");
document.write("    <option value=330900>舟山市                        </option>");
document.write("    <option value=332500>丽水地区                      </option>");
document.write("    <option value=332600>台州地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr12 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=340000>全部                      </option>");
document.write("    <option value=340100>合肥市                        </option>");
document.write("    <option value=340200>芜湖市                        </option>");
document.write("    <option value=340300>蚌埠市                        </option>");
document.write("    <option value=340400>淮南市                        </option>");
document.write("    <option value=340500>马鞍山市                      </option>");
document.write("    <option value=340600>淮北市                        </option>");
document.write("    <option value=340700>铜陵市                        </option>");
document.write("    <option value=340800>安庆市                        </option>");
document.write("    <option value=341000>黄山市                        </option>");
document.write("    <option value=342100>阜阳地区                      </option>");
document.write("    <option value=342200>宿县地区                      </option>");
document.write("    <option value=342300>滁县地区                      </option>");
document.write("    <option value=342400>六安地区                      </option>");
document.write("    <option value=342500>宣城地区                      </option>");
document.write("    <option value=342600>巢湖地区                      </option>");
document.write("    <option value=342900>池州地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr13 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=350000>全部                      </option>");
document.write("    <option value=350100>福州市                        </option>");
document.write("    <option value=350200>厦门市                        </option>");
document.write("    <option value=350300>莆田市                        </option>");
document.write("    <option value=350400>三明市                        </option>");
document.write("    <option value=350500>泉州市                        </option>");
document.write("    <option value=350600>漳州市                        </option>");
document.write("    <option value=352100>南平地区                      </option>");
document.write("    <option value=352200>宁德地区                      </option>");
document.write("    <option value=352600>龙岩地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr14 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=360000>全部                      </option>");
document.write("    <option value=360100>南昌市                        </option>");
document.write("    <option value=360200>景德镇市                      </option>");
document.write("    <option value=360300>萍乡市                        </option>");
document.write("    <option value=360400>九江市                        </option>");
document.write("    <option value=360500>新余市                        </option>");
document.write("    <option value=360600>鹰潭市                        </option>");
document.write("    <option value=362100>赣州地区                      </option>");
document.write("    <option value=362200>宜春地区                      </option>");
document.write("    <option value=362300>上饶地区                      </option>");
document.write("    <option value=362400>吉安地区                      </option>");
document.write("    <option value=362500>抚州地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr15 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=370000>全部                      </option>");
document.write("    <option value=370100>济南市                        </option>");
document.write("    <option value=370200>青岛市                        </option>");
document.write("    <option value=370300>淄博市                        </option>");
document.write("    <option value=370400>枣庄市                        </option>");
document.write("    <option value=370500>东营市                        </option>");
document.write("    <option value=370600>烟台市                        </option>");
document.write("    <option value=370700>潍坊市                        </option>");
document.write("    <option value=370800>济宁市                        </option>");
document.write("    <option value=370900>泰安市                        </option>");
document.write("    <option value=371000>威海市                        </option>");
document.write("    <option value=371100>日照市                        </option>");
document.write("    <option value=372300>惠民地区                      </option>");
document.write("    <option value=372400>德州地区                      </option>");
document.write("    <option value=372500>聊城地区                      </option>");
document.write("    <option value=372800>临沂地区                      </option>");
document.write("    <option value=372900>菏泽地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr16 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=410000>全部                      </option>");
document.write("    <option value=410100>郑州市                        </option>");
document.write("    <option value=410200>开封市                        </option>");
document.write("    <option value=410300>洛阳市                        </option>");
document.write("    <option value=410400>平顶山市                      </option>");
document.write("    <option value=410500>安阳市                        </option>");
document.write("    <option value=410600>鹤壁市                        </option>");
document.write("    <option value=410700>新乡市                        </option>");
document.write("    <option value=410800>焦作市                        </option>");
document.write("    <option value=410900>濮阳市                        </option>");
document.write("    <option value=411000>许昌市                        </option>");
document.write("    <option value=411100>漯河市                        </option>");
document.write("    <option value=411200>三门峡市                      </option>");
document.write("    <option value=412300>商丘地区                      </option>");
document.write("    <option value=412700>周口地区                      </option>");
document.write("    <option value=412800>驻马店地区                    </option>");
document.write("    <option value=412900>南阳地区                      </option>");
document.write("    <option value=413000>信阳地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr17 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=420000>全部                      </option>");
document.write("    <option value=420100>武汉市                        </option>");
document.write("    <option value=420200>黄石市                        </option>");
document.write("    <option value=420300>十堰市                        </option>");
document.write("    <option value=420400>沙市市                        </option>");
document.write("    <option value=420500>宜昌市                        </option>");
document.write("    <option value=420600>襄樊市                        </option>");
document.write("    <option value=420700>鄂州市                        </option>");
document.write("    <option value=420800>荆门市                        </option>");
document.write("    <option value=422100>黄冈地区                      </option>");
document.write("    <option value=422200>孝感地区                      </option>");
document.write("    <option value=422300>咸宁地区                      </option>");
document.write("    <option value=422400>荆州地区                      </option>");
document.write("    <option value=422600>郧阳地区                      </option>");
document.write("    <option value=422700>宜昌地区                      </option>");
document.write("    <option value=422800>鄂西土家族苗族自治州          </option>");
document.write("    <option value=422900>省直辖行政单位                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr18 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=430000>全部                      </option>");
document.write("    <option value=430100>长沙市                        </option>");
document.write("    <option value=430200>株州市                        </option>");
document.write("    <option value=430300>湘潭市                        </option>");
document.write("    <option value=430400>衡阳市                        </option>");
document.write("    <option value=430500>邵阳市                        </option>");
document.write("    <option value=430600>岳阳市                        </option>");
document.write("    <option value=430700>常德市                        </option>");
document.write("    <option value=430800>大庸市                        </option>");
document.write("    <option value=432300>益阳地区                      </option>");
document.write("    <option value=432500>娄底地区                      </option>");
document.write("    <option value=432600>邵阳地区                      </option>");
document.write("    <option value=432800>郴州                          </option>");
document.write("    <option value=432900>零陵地区                      </option>");
document.write("    <option value=433000>怀化地区                      </option>");
document.write("    <option value=433100>湘西土家族苗族自治州          </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr19 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=440000>全部                      </option>");
document.write("    <option value=440100>广州市                        </option>");
document.write("    <option value=440200>韶关市                        </option>");
document.write("    <option value=440300>深圳市                        </option>");
document.write("    <option value=440400>珠海市                        </option>");
document.write("    <option value=440500>汕头市                        </option>");
document.write("    <option value=440600>佛山市                        </option>");
document.write("    <option value=440700>江门市                        </option>");
document.write("    <option value=440800>湛江市                        </option>");
document.write("    <option value=440900>茂名市                        </option>");
document.write("    <option value=441200>肇庆市                        </option>");
document.write("    <option value=441300>惠州市                        </option>");
document.write("    <option value=441400>梅州市                        </option>");
document.write("    <option value=441500>汕尾市                        </option>");
document.write("    <option value=441600>河源市                        </option>");
document.write("    <option value=441700>阳江市                        </option>");
document.write("    <option value=441800>清源市                        </option>");
document.write("    <option value=441900>东莞市                        </option>");
document.write("    <option value=442000>中山市                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr20 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=450000>全部                      </option>");
document.write("    <option value=450100>南宁市                          </option>");
document.write("    <option value=450200>柳州市                          </option>");
document.write("    <option value=450300>桂林市                          </option>");
document.write("    <option value=450400>梧州市                          </option>");
document.write("    <option value=450500>北海市                          </option>");
document.write("    <option value=452100>南宁地区                        </option>");
document.write("    <option value=452200>柳州地区                        </option>");
document.write("    <option value=452300>桂林地区                        </option>");
document.write("    <option value=452400>梧州地区                        </option>");
document.write("    <option value=452500>玉林地区                        </option>");
document.write("    <option value=452600>百色地区                        </option>");
document.write("    <option value=452700>河池地区                        </option>");
document.write("    <option value=452800>钦州地区                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr21 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=460000>全部                      </option>");
document.write("    <option value=460100>海口市                        </option>");
document.write("    <option value=460200>三亚市                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr22 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=500000>全部                      </option>");
document.write("    <option value=500100>重庆市                              </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr23 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=510000>全部                      </option>");
document.write("    <option value=510100>成都市                        </option>");
document.write("    <option value=510300>自贡市                        </option>");
document.write("    <option value=510400>攀枝花市                      </option>");
document.write("    <option value=510500>泸州市                        </option>");
document.write("    <option value=510600>德阳市                        </option>");
document.write("    <option value=510700>绵阳市                        </option>");
document.write("    <option value=510800>广元市                        </option>");
document.write("    <option value=510900>遂宁市                        </option>");
document.write("    <option value=511000>内江市                        </option>");
document.write("    <option value=511100>乐山市                        </option>");
document.write("    <option value=512200>万县                          </option>");
document.write("    <option value=512300>涪陵地区                      </option>");
document.write("    <option value=512500>宜宾地区                      </option>");
document.write("    <option value=512900>南充地区                      </option>");
document.write("    <option value=513000>达县地区                      </option>");
document.write("    <option value=513100>雅安地区                      </option>");
document.write("    <option value=513200>阿坝藏族羌族自治州            </option>");
document.write("    <option value=513300>甘孜藏族自治州                </option>");
document.write("    <option value=513400>凉山彝族自治州                </option>");
document.write("    <option value=513500>黔江地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr24 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=520000>全部                      </option>");
document.write("    <option value=520100>贵阳市                        </option>");
document.write("    <option value=520200>六盘水市                      </option>");
document.write("    <option value=522100>遵义地区                      </option>");
document.write("    <option value=522200>铜仁地区                      </option>");
document.write("    <option value=522300>黔西南布依族苗族自治州        </option>");
document.write("    <option value=522400>毕节地区                      </option>");
document.write("    <option value=522500>安顺地区                      </option>");
document.write("    <option value=522600>黔东南苗族侗族自治州          </option>");
document.write("    <option value=522700>黔南布依族苗族自治州          </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr25 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=530000>全部                      </option>");
document.write("    <option value=530100>昆明市                        </option>");
document.write("    <option value=530200>东川市                        </option>");
document.write("    <option value=532100>昭通地区                      </option>");
document.write("    <option value=532200>曲靖地区                      </option>");
document.write("    <option value=532300>楚雄彝族自治州                </option>");
document.write("    <option value=532400>玉溪地区                      </option>");
document.write("    <option value=532500>红河哈尼族彝族自治州          </option>");
document.write("    <option value=532600>文山壮族苗族自治州            </option>");
document.write("    <option value=532700>思茅地区                      </option>");
document.write("    <option value=532800>西双版纳傣族自治州            </option>");
document.write("    <option value=532900>大理白族自治州                </option>");
document.write("    <option value=533000>保山地区                      </option>");
document.write("    <option value=533100>德宏傣族景颇族自治州          </option>");
document.write("    <option value=533200>丽江地区                      </option>");
document.write("    <option value=533300>怒江傈僳族自治州              </option>");
document.write("    <option value=533400>迪庆藏族自治州                </option>");
document.write("    <option value=533500>临沧地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr26 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=540000>全部                      </option>");
document.write("    <option value=540100>拉萨市                          </option>");
document.write("    <option value=542100>昌都地区                        </option>");
document.write("    <option value=542200>山南地区                        </option>");
document.write("    <option value=542300>日喀则地区                      </option>");
document.write("    <option value=542400>那曲地区                        </option>");
document.write("    <option value=542500>阿里地区                        </option>");
document.write("    <option value=542600>林芝地区                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr27 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=610000>全部                      </option>");
document.write("    <option value=610100>西安市                        </option>");
document.write("    <option value=610200>铜川市                        </option>");
document.write("    <option value=610300>宝鸡市                        </option>");
document.write("    <option value=610400>咸阳市                        </option>");
document.write("    <option value=612100>渭南地区                      </option>");
document.write("    <option value=612300>汉中地区                      </option>");
document.write("    <option value=612400>安康地区                      </option>");
document.write("    <option value=612500>商洛地区                      </option>");
document.write("    <option value=612600>延安地区                      </option>");
document.write("    <option value=612700>榆林地区                      </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr28 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=620000>全部                      </option>");
document.write("    <option value=620100>兰州市                        </option>");
document.write("    <option value=620200>嘉峪关市                      </option>");
document.write("    <option value=620300>金昌市                        </option>");
document.write("    <option value=620400>白银市                        </option>");
document.write("    <option value=620500>天水市                        </option>");
document.write("    <option value=622100>酒泉地区                      </option>");
document.write("    <option value=622200>张掖地区                      </option>");
document.write("    <option value=622300>武威地区                      </option>");
document.write("    <option value=622400>定西地区                      </option>");
document.write("    <option value=622600>陇南地区                      </option>");
document.write("    <option value=622700>平凉地区                      </option>");
document.write("    <option value=622800>庆阳地区                      </option>");
document.write("    <option value=622900>临夏回族自治州                </option>");
document.write("    <option value=623000>甘南藏族自治州                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr29 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=630000>全部                      </option>");
document.write("    <option value=630100>西宁市                        </option>");
document.write("    <option value=632100>海东地区                      </option>");
document.write("    <option value=632200>海北藏族自治州                </option>");
document.write("    <option value=632300>黄南藏族自治州                </option>");
document.write("    <option value=632500>海南藏族自治州                </option>");
document.write("    <option value=632600>果洛藏族自治州                </option>");
document.write("    <option value=632700>玉树藏族自治州                </option>");
document.write("    <option value=632800>海西蒙古族藏族自治州          </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr30 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=640000>全部                      </option>");
document.write("    <option value=640100>银川市                          </option>");
document.write("    <option value=640200>石咀山市                        </option>");
document.write("    <option value=642100>银南地区                        </option>");
document.write("    <option value=642200>固原地区                        </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr31 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=650000>全部                      </option>");
document.write("    <option value=650100>乌鲁木齐市                      </option>");
document.write("    <option value=650200>克拉玛依市                      </option>");
document.write("    <option value=652100>吐鲁番地区                      </option>");
document.write("    <option value=652200>哈密地区                        </option>");
document.write("    <option value=652300>昌吉回族自治州                  </option>");
document.write("    <option value=652700>博尔塔拉蒙古自治州              </option>");
document.write("    <option value=652800>巴音郭楞蒙古自治州              </option>");
document.write("    <option value=652900>阿克苏地区                      </option>");
document.write("    <option value=653000>克孜勒苏柯尔克孜自治州          </option>");
document.write("    <option value=653100>喀什地区                        </option>");
document.write("    <option value=653200>和田地区                        </option>");
document.write("    <option value=654000>伊梨哈萨克自治州                </option>");
document.write("    <option value=654100>伊犁地区                        </option>");
document.write("    <option value=654200>塔城地区                        </option>");
document.write("    <option value=654300>阿勒泰地区                      </option>");
document.write("    <option value=659000>省直辖行政单位                  </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr32 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=710000>台湾                                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr33 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>");
document.write("    <option value=720000>香港                                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("        <tr id=tr34 style='display:none' align='left' > ");
document.write("          <td> ");
document.write("      <select name='xzqhdm' onclick='document.all.xzqh.value=this.value'>    <option value=730000>澳门                                </option>");
document.write("          </td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </td>");
document.write("  </tr>");
document.write("</table>");
document.write("<input type='text' name='xzqh' value='000000' style='display:none'>");
document.write("<script language='javascript'>");
document.write("tr0.style.display=''");
document.write("</script>");